version: 2.1

orbs:
  dependency-tracking: cci-dep/dependency-tracking@0.0.1

jobs:
  example-job:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - run:
          name: Generate URL
          command: echo "https://api.circleci.com/private/dependencies/deps-per-pipeline?pipelineId=<< pipeline.id >>"
      - dependency-tracking/track:
          path: package-lock.json
          pipeline_id: << pipeline.id >>
          revision: << pipeline.git.revision >>		  
          vcs_url: << pipeline.project.git_url >>

workflows:
  example-workflow:
    jobs:
      - example-job